[project]
name = "GitRepoBackup"
version = "1.0.0"
description = "GitRepoBackup is a utility for backup only files managed by git repositories."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fire>=0.7.0",
    "gitpython>=3.1.44",
    "tqdm>=4.67.1",
]
